package suite

import (
	"path/filepath"
	"runtime"
	"testing"

	"github.com/thlaurentino/arit/internal/analyzer"
	"github.com/thlaurentino/arit/internal/config"
	"github.com/thlaurentino/arit/internal/reader"
	"github.com/thlaurentino/arit/internal/rules/semantics"
	"github.com/thlaurentino/arit/internal/test/framework"
)

func TestMacroExpansion(t *testing.T) {
	// Enable the experimental flag specifically for this test
	originalFlag := analyzer.EnableExperimentalMacroExpansion
	analyzer.EnableExperimentalMacroExpansion = true
	defer func() { analyzer.EnableExperimentalMacroExpansion = originalFlag }()

	framework.RunRuleTest(t, framework.RuleTestCase{
		FileToAnalyze: "macro_expansion.clj",
		RuleID:        "unnecessary-into",
		ExpectedFindings: []framework.ExpectedFinding{
			{StartLine: 4},
		},
		ForbiddenFindings: []framework.ExpectedFinding{
			{StartLine: 9},
		},
	})
}

func TestMacroExpansionUsesDerivedTreeAndTracksOrigin(t *testing.T) {
	_, sourceFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("could not locate the regression test source")
	}
	path := filepath.Clean(filepath.Join(filepath.Dir(sourceFile), "../data/macro_expansion.clj"))
	index := semantics.NewProjectIndex()
	if err := index.IndexFile(path); err != nil {
		t.Fatalf("index macro fixture: %v", err)
	}
	originalRoots, _, ok := index.CachedFile(path)
	if !ok {
		t.Fatal("expected indexed macro fixture")
	}

	previous := analyzer.EnableExperimentalMacroExpansion
	analyzer.EnableExperimentalMacroExpansion = true
	t.Cleanup(func() { analyzer.EnableExperimentalMacroExpansion = previous })
	result, err := analyzer.NewAnalyzer(&config.Config{
		EnabledRules:  map[string]bool{},
		EnabledGroups: map[string]bool{},
		RuleConfig:    map[string]config.RuleSettings{},
	}).AnalyzeFileWithProjectIndex(path, index)
	if err != nil {
		t.Fatalf("analyze macro fixture: %v", err)
	}
	if len(result.RichRoots) == 0 || result.RichRoots[0] == originalRoots[0] {
		t.Fatal("experimental expansion reused and mutated the indexed AST")
	}

	var generated int
	var visit func(*reader.RichNode)
	visit = func(node *reader.RichNode) {
		if node == nil {
			return
		}
		if node.Generated {
			generated++
			if !isSupportedGeneratedMacro(node.GeneratedBy) {
				t.Fatalf("unexpected macro provenance: %#v", node)
			}
			if node.Origin == nil {
				t.Fatal("generated node has no source origin")
			}
		}
		for _, child := range node.Children {
			visit(child)
		}
	}
	for _, root := range result.RichRoots {
		visit(root)
	}
	if generated == 0 {
		t.Fatal("expected at least one derived node from thread macro expansion")
	}

	var originalGenerated bool
	var checkOriginal func(*reader.RichNode)
	checkOriginal = func(node *reader.RichNode) {
		if node == nil {
			return
		}
		if node.Generated {
			originalGenerated = true
			return
		}
		for _, child := range node.Children {
			checkOriginal(child)
		}
	}
	for _, root := range originalRoots {
		checkOriginal(root)
	}
	if originalGenerated {
		t.Fatal("indexed AST was marked as generated by experimental expansion")
	}
}

func isSupportedGeneratedMacro(name string) bool {
	switch name {
	case "->", "->>", "some->", "some->>", "cond->", "cond->>":
		return true
	default:
		return false
	}
}

func TestExtendedThreadingMacroExpansionTracksProvenance(t *testing.T) {
	previous := analyzer.EnableExperimentalMacroExpansion
	analyzer.EnableExperimentalMacroExpansion = true
	t.Cleanup(func() { analyzer.EnableExperimentalMacroExpansion = previous })

	path := filepath.Join("../data", "macro_expansion_extended.clj")
	result, err := analyzer.AnalyzeFile(path, &config.Config{
		EnabledRules: map[string]bool{},
		RuleConfig:   map[string]config.RuleSettings{},
	})
	if err != nil {
		t.Fatalf("analyze extended macro fixture: %v", err)
	}

	wanted := map[string]bool{"some->": false, "some->>": false, "cond->": false, "cond->>": false}
	var invalidConditionalUnchanged bool
	var quotedFormGenerated bool
	var visit func(*reader.RichNode, bool)
	visit = func(node *reader.RichNode, inQuotedForm bool) {
		if node == nil {
			return
		}
		if inQuotedForm && node.Generated {
			quotedFormGenerated = true
		}
		if _, ok := wanted[node.GeneratedBy]; ok {
			wanted[node.GeneratedBy] = true
			if node.Origin == nil {
				t.Fatalf("generated %s node has no origin", node.GeneratedBy)
			}
		}
		if node.Type == reader.NodeList && len(node.Children) > 0 && node.Children[0] != nil && node.Children[0].Type == reader.NodeSymbol {
			if node.Children[0].Value == "cond->" && len(node.Children) == 5 {
				invalidConditionalUnchanged = true
			}
		}
		childQuoted := inQuotedForm || node.Type == reader.NodeQuote || node.Type == reader.NodeSyntaxQuote || node.Type == reader.NodeVarQuote
		for _, child := range node.Children {
			visit(child, childQuoted)
		}
	}
	for _, root := range result.RichRoots {
		visit(root, false)
	}
	for macro, found := range wanted {
		if !found {
			t.Errorf("expected provenance for %s", macro)
		}
	}
	if !invalidConditionalUnchanged {
		t.Fatal("invalid odd-arity cond-> form was expanded")
	}
	if quotedFormGenerated {
		t.Fatal("quoted threading form was expanded")
	}
}
